/* https://www.w3.org/TR/xml/#sec-notation */

insertInto ::=
(
    (
        'withIdentifiableConvertedVia'
        pojoInsert
        'executeAndConvertVia'
    )
    |
    (
        'withIdentifiableConvertedUsing'
        pojoInsert
        'executeAndConvert'
    )
    |
    (
        'withAnonymousConvertedVia'
        pojoInsert
        'executeAndConvertVia'
    )
    |
    (
        'withAnonymousConvertedUsing'
        pojoInsert
        'executeAndConvert'
    )
)

pojoInsert ::=
(
    'fromPojo'

    (
        'generating'
        |
        adjustments
    )
    *
)

update ::=
(
    'withRecordConvertedVia'
    pojoUpdate
    'executeAndConvertVia'

    |

    'withRecordConvertedUsing'
    pojoUpdate
    'executeAndConvert'

    |

    'withPrimaryKey'
    sparseUpdate
    'execute'
)

pojoUpdate ::=
(
    'fromNewPojo'

    (
        'andExistingPojo'
        (
            'predetectCollisionOn'
            |
            checks
        )
        *

        |

        checks
        *
    )
    ?

    (
        'postDetectCollisionIf'
        |
        adjustments
    )
    *
)

sparseUpdate ::=
(
    (
        'set' | 'increase' | 'refresh'
    )
    +

    'postDetectCollisionIf'
    *
)

adjustments ::= 'adjusting' | 'normalizingEmail'

checks ::=
(
    'verifyUnchanged'
    |
    'checkAndRandomize'
    |
    'checkAndIncrease'
    |
    'checkAndRefresh'
)


selectFrom ::=
(
    (
        'convertedVia' | 'convertedUsing'
    )

    (
        (
            (
                (
                    'read'
                    'filter'?
                )
                |
                'findWhere'
            )
            'fetchOptional'
        )
        |
        (
            'list'
            'filter'?
            'orderBy'?
            'fetchStream'
        )
    )
)

query ::=
(
    (
        (
            'convertedVia' | 'convertedUsing'
        )

        (
            'fetchOptional' | 'fetchStream'
        )
    )
    |
    (
        'skipConversion'

        (
            'fetchRecordOptional' | 'fetchRecordStream'
        )
    )
)
