/* https://www.w3.org/TR/xml/#sec-notation */

insertInto ::=
(
    (
        (
            'withIdentifiableConvertedVia'
            |
            'withAnonymousConvertedVia'
        )
        pojoInsert
        (
            'executeAndConvertVia'
            |
            'voidExecute'
        )
    )
    |
    (
        (
            'withIdentifiableConvertedUsing'
            |
            'withAnonymousConvertedUsing'
        )
        pojoInsert
        (
            'executeAndConvert'
            |
            'voidExecute'
        )
    )
)

pojoInsert ::=
(
    'fromPojo'

    (
        'generating'
        |
        adjustments
    )
    *
)

update ::=
(
    'withRecordConvertedVia'
    pojoUpdate
    (
        'executeAndConvertVia'
        |
        'voidExecute'
    )

    |

    'withRecordConvertedUsing'
    pojoUpdate
    (
        'executeAndConvert'
        |
        'voidExecute'
    )

    |

    'withPrimaryKey'
    sparseUpdate
    'voidExecute'
)

pojoUpdate ::=
(
    'fromNewPojo'

    (
        'andExistingPojo'
        (
            'predetectCollisionOn'
            |
            checks
        )
        *

        |

        checks
        *
    )
    ?

    (
        'postDetectCollisionIf'
        |
        adjustments
    )
    *
)

sparseUpdate ::=
(
    (
        'set' | 'increase' | 'refresh'
    )
    +

    'postDetectCollisionIf'
    *
)

adjustments ::= 'adjusting' | 'normalizingEmail'

checks ::=
(
    'verifyUnchanged'
    |
    'checkAndRandomize'
    |
    'checkAndIncrease'
    |
    'checkAndRefresh'
)


selectFrom ::=
(
    (
        'convertedVia' | 'convertedUsing'
    )

    (
        (
            (
                (
                    'read'
                    'filter'?
                )
                |
                'findWhere'
            )
            'fetchOptional'
        )
        |
        (
            'list'
            'filter'?
            'orderBy'?
            'fetchStream'
        )
    )
)

query ::=
(
    (
        (
            'convertedVia' | 'convertedUsing'
        )

        (
            'fetchOptional' | 'fetchStream'
        )
    )
    |
    (
        'skipConversion'

        (
            'fetchRecordOptional' | 'fetchRecordStream'
        )
    )
)
