/* https://www.w3.org/TR/xml/#sec-notation */

insertInto ::=
(
    'withIdentifiableConvertedVia' | 'withAnonymousConvertedVia'
)

'fromPojo'

(
    'generating'
    |
    adjustments
)
*

'executeAndConvert'



update ::=
(
    'withRecordConvertedVia'

    'fromNewPojo'

    (
        'andExistingPojo'
        (
            'predetectCollisionOn'
            |
            checks
        )
        *

        |

        checks
        *
    )
    ?

    (    
        'postDetectCollisionIf'
        |
        adjustments
    )
    *
    
    'executeAndConvert'

    |

    'withPrimaryKey'
    (
        'set' | 'increase' | 'refresh'
    )
    +
    
    'postDetectCollisionIf'
    *
    
    'execute'
)

adjustments ::= 'adjusting' | 'normalizingEmail'

checks ::=
(
    'verifyUnchanged'
    |
    'checkAndRandomize'
    |
    'checkAndIncrease'
    |
    'checkAndRefresh'
)
