/* https://www.w3.org/TR/xml/#sec-notation */

insertInto ::=
(
    singleInsert
    |
    batchInsert
)

singleInsert ::=
(
    (
        (
            (
                'withIdentifiableConvertedUsing'
                identifiablePojoInsert
            )
            |
            (
                'withCustomKeyedConvertedUsing'
                customKeyedPojoInsert
            )
        )
        (
            'executeAndConvert'
            |
            'voidExecute'
        )
    )
    |
    (
        (
            (
                'withIdentifiableConvertedVia'
                identifiablePojoInsert
            )
            |
            (
                'withCustomKeyedConvertedVia'
                customKeyedPojoInsert
            )
        )
        (
            'executeAndConvertVia'
            |
            'voidExecute'
        )
    )
)

batchInsert ::=
(
    (
        (
            (
                'withIdentifiableConvertedUsing'
                |
                'withIdentifiableConvertedVia'
            )
            identifiablePojoBatchInsert
        )
        |
        (
            (
                'withCustomKeyedConvertedUsing'
                |
                'withCustomKeyedConvertedVia'
            )
            customKeyedPojoBatchInsert
        )
    )
    'voidExecute'
)

identifiablePojoInsert ::=
(
    (
        'fromPojo'
        (
            'generating'
            |
            adjustments
        )
        *
    )
    |
    (
        'fromPojoWithPresetId'

        (
            'generating'
            |
            adjustments
        )
        *

        'onDuplicateKeyIgnore'?
    )
)

identifiablePojoBatchInsert ::=
(
    (
        'fromPojos'
        |
        'fromPojosWithPresetId'
    )
    (
        'generating'
        |
        adjustments
    )
    *
)

customKeyedPojoInsert ::=
(
    'fromPojo'

    (
        'generating'
        |
        adjustments
    )
    *

    'onDuplicateKeyIgnore'?
)

customKeyedPojoBatchInsert ::=
(
    'fromPojos'
    (
        'generating'
        |
        adjustments
    )
    *
)

update ::=
(
    'withRecordConvertedVia'
    pojoUpdate
    (
        'executeAndConvertVia'
        |
        'voidExecute'
    )

    |

    'withRecordConvertedUsing'
    pojoUpdate
    (
        'executeAndConvert'
        |
        'voidExecute'
    )

    |

    'withPrimaryKey'
    sparseUpdate
    'voidExecute'
)

pojoUpdate ::=
(
    'fromNewPojo'

    (
        'andExistingPojo'
        (
            'predetectCollisionOn'
            |
            checks
        )
        *

        |

        checks
        *
    )
    ?

    (
        'postDetectCollisionIf'
        |
        adjustments
    )
    *
)

sparseUpdate ::=
(
    (
        'set' | 'increase' | 'refresh'
    )
    +

    'postDetectCollisionIf'
    *
)

adjustments ::= 'adjusting' | 'normalizingEmail'

checks ::=
(
    'verifyUnchanged'
    |
    'checkAndRandomize'
    |
    'checkAndIncrease'
    |
    'checkAndRefresh'
)


selectFrom ::=
(
    (
        'convertedVia' | 'convertedUsing'
    )

    (
        (
            (
                (
                    'read'
                    'filter'?
                )
                |
                'findWhere'
            )
            'fetchOptional'
        )
        |
        (
            'list'
            'filter'?
            'orderBy'?
            'fetchStream'
        )
    )
)

query ::=
(
    (
        (
            'convertedVia' | 'convertedUsing'
        )

        (
            'fetchOptional' | 'fetchStream'
        )
    )
    |
    (
        'skipConversion'

        (
            'fetchRecordOptional' | 'fetchRecordStream'
        )
    )
)

delete ::=
(
    'fromIdentifiable'
    'withId'
    'denyUnless'?
    (
        (
            'voidExecute'
            |
            'executeAndConvert'
        )
        |
        (
            'ignoreIfNotFound'
            (
                'tryExecute'
                |
                'tryExecuteAndConvert'
            )
        )
    )
)
